'use client';
import Image from 'next/image';
import {useEffect,useState} from 'react';
import type {Anime} from '../lib/jikan';
import {poster} from '../lib/jikan';
import VideoStudio from '../components/video-studio';

const sections=[['Trending','/top/anime?limit=12'],['Top Rated','/top/anime?filter=bypopularity&limit=12'],['Airing Now','/anime?status=airing&order_by=score&sort=desc&limit=12'],['Upcoming','/seasons/upcoming?limit=12']] as const;
function Card({a,onOpen}:{a:Anime;onOpen:(a:Anime)=>void}){return <button className="card" onClick={()=>onOpen(a)}><div className="poster"><Image src={poster(a)} alt={a.title} fill sizes="(max-width:720px) 145px, 170px"/><span className="score">★ {a.score??'—'}</span></div><div className="cardBody"><div className="title">{a.title}</div><div className="meta">{a.type||'Anime'} · {a.episodes??'?'} eps</div></div></button>}
function Skeletons(){return <div className="rail">{Array.from({length:7},(_,i)=><div className="skeleton skeletonCard" key={i}/>)}</div>}
function Section({name,path,data,loading,error,onRetry,onOpen}:{name:string;path:string;data:Anime[]|undefined;loading:boolean;error:string;onRetry:()=>void;onOpen:(a:Anime)=>void}){return <section className="section"><div className="sectionHead"><h2>{name}</h2><span className="muted">{loading?'Loading…':'Live catalog'}</span></div>{loading&&!data&&<Skeletons/>}{error?<div className="errorBox">{error} <button className="secondary" onClick={onRetry}>Retry</button></div>:data&&<div className="rail">{data.map(a=><Card key={a.mal_id} a={a} onOpen={onOpen}/>)}</div>}</section>}
export default function Home(){const [data,setData]=useState<Record<string,Anime[]>>({});const [hero,setHero]=useState<Anime|null>(null);const [loading,setLoading]=useState<Record<string,boolean>>({});const [errors,setErrors]=useState<Record<string,string>>({});const [query,setQuery]=useState('');const [search,setSearch]=useState<Anime[]|null>(null);const [searching,setSearching]=useState(false);const [selected,setSelected]=useState<Anime|null>(null);
const load=async(name:string,path:string)=>{setLoading(x=>({...x,[name]:true}));setErrors(x=>({...x,[name]:''}));try{const r=await fetch('/api/jikan'+path,{cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.error||'Request failed');setData(x=>({...x,[name]:d.data||[]}));if(name==='Trending')setHero(d.data?.[0]||null)}catch(e){setErrors(x=>({...x,[name]:e instanceof Error?e.message:'Unable to load this section.'}))}finally{setLoading(x=>({...x,[name]:false}))}};
useEffect(()=>{sections.forEach(([n,p],i)=>window.setTimeout(()=>load(n,p),i*120));},[]);
const doSearch=async()=>{const q=query.trim();if(!q)return;setSearching(true);setSearch(null);try{const r=await fetch('/api/jikan/anime?q='+encodeURIComponent(q)+'&limit=24',{cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.error||'Search failed');setSearch(d.data||[]);document.getElementById('browse')?.scrollIntoView({behavior:'smooth'})}catch(e){setErrors(x=>({...x,search:e instanceof Error?e.message:'Search failed.'}))}finally{setSearching(false)}};
return <div className="shell"><nav className="nav"><b className="logo">KAGE</b><div className="navlinks"><button onClick={()=>scrollTo(0,0)}>Home</button><button onClick={()=>document.getElementById('browse')?.scrollIntoView()}>Browse</button><button onClick={()=>document.getElementById('schedule')?.scrollIntoView()}>Schedule</button><button onClick={()=>document.getElementById('ai-studio')?.scrollIntoView()}>AI Studio</button></div><form className="search" onSubmit={e=>{e.preventDefault();doSearch()}}><input aria-label="Search anime" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search anime…"/><button aria-label="Search">⌕</button></form></nav>
{hero?<section className="hero" style={{backgroundImage:`url(${poster(hero)})`}}><div className="heroCopy"><div className="eyebrow">Featured</div><h1>{hero.title}</h1><div className="stats"><span>★ <b>{hero.score??'—'}</b></span><span>{hero.type||'TV'}</span><span>{hero.episodes??'?'} episodes</span><span>{hero.year??'—'}</span></div><p>{hero.synopsis?.slice(0,340)||'Discover your next favorite anime.'}</p><div className="actions"><button className="primary" onClick={()=>setSelected(hero)}>View details</button></div></div></section>:<section className="hero"><div className="heroCopy"><div className="eyebrow">KAGE</div><h1>Your anime, organized.</h1><p>Live sections are loading independently. You can start browsing as soon as each section arrives.</p></div></section>}
{(search||searching)&&<section className="section" id="browse"><div className="sectionHead"><h2>Search results</h2><span className="muted">{searching?'Searching…':`${search?.length||0} results`}</span></div>{searching?<Skeletons/>:search?.length?<div className="grid">{search.map(a=><Card key={a.mal_id} a={a} onOpen={setSelected}/>)}</div>:<div className="empty">No matching anime found.</div>}</section>}
{sections.map(([name,path])=><Section key={name} name={name} path={path} data={data[name]} loading={!!loading[name]} error={errors[name]||''} onRetry={()=>load(name,path)} onOpen={setSelected}/>)}
<section className="section" id="browse"><div className="sectionHead"><h2>Browse</h2><span className="muted">Search any title above</span></div><div className="empty">Search for an anime to populate this area with results.</div></section>
<VideoStudio/><section className="section" id="schedule"><div className="sectionHead"><h2>Schedule</h2><span className="muted">Coming from the live data layer</span></div><div className="empty">The schedule surface is ready; the next pass will connect weekly broadcast data without blocking the homepage.</div></section><footer className="footer">KAGE · Anime discovery powered by Jikan. KAGE does not provide unauthorized streaming.</footer>{selected&&<Detail a={selected} onClose={()=>setSelected(null)}/>}</div>}
function Detail({a,onClose}:{a:Anime;onClose:()=>void}){const [full,setFull]=useState<Anime|null>(null);const [busy,setBusy]=useState(true);useEffect(()=>{let live=true;setBusy(true);fetch('/api/jikan/anime/'+a.mal_id+'/full').then(r=>r.json()).then(x=>{if(live)setFull(x.data||a)}).catch(()=>{if(live)setFull(a)}).finally(()=>live&&setBusy(false));return()=>{live=false}},[a]);const d=full||a;return <div className="dialogBack" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><div className="dialog"><button className="close" aria-label="Close" onClick={onClose}>×</button><div className="detail"><Image src={poster(d)} alt={d.title} width={220} height={330}/><div>{busy&&<div className="muted">Loading full details…</div>}<div className="eyebrow">{d.type||'Anime'} · {d.status||''}</div><h1>{d.title}</h1><div className="stats"><span>★ <b>{d.score??'—'}</b></span><span>Rank #{d.rank??'—'}</span><span>{d.episodes??'?'} episodes</span></div><div className="chips">{d.genres?.map(g=><span className="chip" key={g.mal_id}>{g.name}</span>)}</div><p>{d.synopsis||'No synopsis available.'}</p><div className="actions"><button className="primary" onClick={()=>d.url&&window.open(d.url,'_blank')}>Open MAL</button>{d.trailer?.url&&<button className="secondary" onClick={()=>window.open(d.trailer?.url||'','_blank')}>Trailer</button>}</div></div></div></div></div>}
